### ISSUE TITLE
ModuleNotFoundError: No module named 'actions.secrets'

### ISSUE THREAD

**Issue by owos** [jpwakugawa/chatbot-hogwarts#2]
Hello, tried deploying this to Okteto but I go the following error. I also got an error deploying docker compose.

**Comment by jpwakugawa** [comment]
Thanks for the issue!

I'll improve the documentation about this part.

Go to `bot`  >  `actions`:
Add a secrets.py file with your mongo cluster information.
```python3
secrets = {
    "CLUSTER": "your_cluster",
    "DB_NAME": "your_database",
    "COL_NAME": "your_collection"
}
```

**Comment by owos** [comment]
great, thank you for the update.

**Comment by owos** [comment]
Thank you. I'm having an issue with changing my bot server port I need to
change it from 5005 to something else. You know any solution for that?

**Comment by jpwakugawa** [comment]
Hello, you could change the forwarded port at docker-compose **ports**:
![image](https://user-images.githubusercontent.com/68277391/195958988-a0706520-a23c-437c-8cc1-363fb6d7e732.png)
Or even pass the select port as argument:
```
rasa run --enable-api --cors "*" -p 5010
```

**Comment by owos** [comment]
Hi, I've been able to fix this for a while now. My current issue is getting the chat widget to show up on the main page. it never comes up.

**Comment by jpwakugawa** [comment]
Are you getting any errors?
Changing the socketUrl like I did here should be enough:
![image](https://user-images.githubusercontent.com/68277391/195960501-b6225fd3-f155-46a2-a913-6c648322b7c9.png)

**Comment by owos** [comment]
So the issue is that I forked your repo and deployed it exactly on okteto and the chat widget did not pop up, I removed the secrets as I do not have any secrets. here's the link of the outceome: https://web-owos.cloud.okteto.net/

**Comment by jpwakugawa** [comment]
I have just redeployed my repo and it worked normally, make sure you are using the correct endpoint at socketUrl, in your case it should be something like *bot-owos.cloud.okteto.net* and deploy using this command:
```bash
 okteto deploy --build
```
Also, if you are going to use rasa-sdk, don't forget to change the endpoint:
![image](https://user-images.githubusercontent.com/68277391/196012529-d652a384-a25e-43df-a5b1-70e6663ec211.png)
If this doesn't work, show me the logs from your pod at Okteto.
![image](https://user-images.githubusercontent.com/68277391/196012655-f3cf70b4-6314-486a-b05d-11301bccf2ce.png)
